---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: analytics
  name: spark-k8s-driver
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "configmaps"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["services","persistentvolumeclaims","secrets"]
  verbs: ["get", "watch", "list"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-psp-rb
  namespace: analytics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: privileged-psp
subjects:
- kind: ServiceAccount
  name: spark-driver
  namespace: analytics



---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-driver-rbac-rb
  namespace: analytics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-k8s-driver
subjects:
- kind: ServiceAccount
  name: spark-driver
  namespace: analytics