apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebook-data
  namespace: analytics
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-cephfs