apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: jupyter-notebook
  namespace: analytics
spec:
  rules:
  - host: jnb.eu-west-1.klovercloud.io
    http:
      paths:
      - backend:
          serviceName: jupyter-notebook
          servicePort: 8888
        path: /
  tls:
  - hosts:
    - jnb.eu-west-1.klovercloud.io
    secretName: wild-certificate-eu-west-1-secret